var test = require('./auth_header')

console.log(test.parse("JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvc2V0ZTIiLCJwZXJtaXNzaW9ucyI6InVzZXIiLCJleHAiOjE0ODY3NTQwMTMsImlhdCI6MTQ4Njc1Mzk5OH0.kBXas8apH3Zg-WsRuyo6s9rkRtCOJfwJDge_xJWw0qY"))
